[package]
name = "voyageai-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
http-client = { git = "https://github.com/fdionisi/http-client", rev = "033ac96ab12ac3d13b78f9725b237380917c7094" }
secrecy = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.63"
